placementdashboard/dashboard/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'Placement Dashboard'

urlpatterns = [
    path('', views.user_login, name='user_login'),
    # url(r'^user_login/$',views.user_login,name='user_login'),
    url('csv', views.getfile, name = 'download_csv'),
    url('getSelfPlaced', views.getSelfPlaced, name = 'getSelfPlaced'),
    url('getDrivesReport', views.getDrivesReport, name = 'getDrivesReport')
]

placementdashboard/placementdashboard/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from dashboard import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^login$',views.user_login,name='user_login'),
    url(r'^index$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dashboard/',include('dashboard.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^requirements/$', views.requirements, name='requirements'),
    url(r'^activedrives$', views.activeDrives, name='activeDrives'),
    url(r'^selfplaced$', views.selfPlaced, name= 'selfPlaced'),
    url(r'^drivesReport', views.drivesReport, name = 'drivesReport'),
    url(r'^', include('dashboard.urls', namespace="dashboard"))
]

placementdashboard/dashboard/forms.py
from django import forms
from dashboard.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')

class UserProfileInfoForm(forms.ModelForm):
    class meta():
        model = UserProfileInfo
        fields = ('portfolio_site')
    

placementdashboard/dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django import forms
from datetime import datetime

from dashboard.forms import UserForm, UserProfileInfoForm
from dashboard.models import Requirements
from dashboard.models import PmaDemand
from dashboard.models import PmaPartner
from dashboard.models import SelfPlaced
from dashboard.models import ActiveDrives
from dashboard.models import DrivesReport
import csv
from django.utils.encoding import smart_str

def index(request):
    return render(request, 'dashboard/index.html')

def requirements(request):
    return render(request, 'dashboard/requirements.html')

def selfPlaced(request):
    selfPlacedStudents = None
    return render(request, 'dashboard/selfPlaced.html', {'selfPlacedStudents' : selfPlacedStudents})

def getSelfPlaced(request):
    batchID = request.POST.get('batch ID')
    print(batchID)
    selfPlacedStudents = SelfPlaced.objects.raw(
        'SELECT firstName, lastName, batch, id, skill, selfPlacedWith, email, mobile, '
        'lastGradYear, collegeName from pma_trainee where selfPlacedWith IS NOT NULL '
        'AND selfPlacedWith NOT LIKE \"\"'
        ' AND batch = \'' + batchID + '\';'
    )
    return render(request, 'dashboard/selfPlaced.html', {'selfPlacedStudents' : selfPlacedStudents})

def activeDrives(request):
    activeDrives = ActiveDrives.objects.raw(
        'SELECT drive_fk as id, @a := @a + 1 slno, name, date FROM pma_selection_round '
        'INNER JOIN pma_drive ON drive_fk = pma_drive.id, (select @a := 0) '
        'as a where roundNumber = 0;'
    )
    for drive in activeDrives:
        print(drive.slno)
    return render(request, 'dashboard/activeDrives.html', {'activeDrives' : activeDrives})

def drivesReport(request):
    drives = None
    return render(request, 'dashboard/drivesReport.html', {'drives' : drives})

def getDrivesReport(request):
    startdate = request.POST.get('startDate')
    enddate = request.POST.get('endDate')
    print(startdate)
    startdate = datetime.strptime(startdate, "%Y-%m-%d").strftime("%d-%m-%Y")
    enddate = datetime.strptime(enddate , "%Y-%m-%d").strftime("%d-%m-%Y")
    print('SELECT pma_selection_round.id, date, pma_drive.name, roundNumber, skills, numberOfPositions, '
        'compensation,rounds FROM pma_selection_round INNER JOIN pma_drive '
        'ON drive_fk = pma_drive.id INNER JOIN pma_demand_skills ON demand_fk '
        '= demand_id INNER JOIN pma_demand ON demand_fk = pma_demand.id '
        'INNER JOIN pma_drive_rounds on roundNumber = round_num AND '
        'drive_id = drive_fk WHERE row(drive_fk,roundNumber) IN '
        '(SELECT drive_fk,max(roundNumber) FROM pma_selection_round GROUP BY '
        'drive_fk) AND date between \'' + startdate + '\' AND \'' + enddate + '\';')
    drives = DrivesReport.objects.raw(
        'SELECT pma_selection_round.id, date, pma_drive.name, roundNumber, skills, numberOfPositions, '
        'compensation,rounds FROM pma_selection_round INNER JOIN pma_drive '
        'ON drive_fk = pma_drive.id INNER JOIN pma_demand_skills ON demand_fk '
        '= demand_id INNER JOIN pma_demand ON demand_fk = pma_demand.id '
        'INNER JOIN pma_drive_rounds on roundNumber = round_num AND '
        'drive_id = drive_fk WHERE row(drive_fk,roundNumber) IN '
        '(SELECT drive_fk,max(roundNumber) FROM pma_selection_round GROUP BY '
        'drive_fk) AND date between \'' + startdate + '\' AND \'' + enddate + '\';'
    )

    for drive in drives:
        print(drive.rounds)
    return render(request, 'dashboard/drivesReport.html', {'drives' : drives})

def getfile(request):
    startdate = request.POST.get('startDate')
    enddate = request.POST.get('endDate')
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="requirements.csv"'
    writer = csv.writer(response, csv.excel)
    response.write(u'\ufeff'.encode('utf8'))
    writer.writerow([
		smart_str(u"Sl No"),
		smart_str(u"Date of requirement"),
        smart_str(u"Partner"),
		smart_str(u"Job Title"),
        smart_str(u"Skills"),
		smart_str(u"Gender"),
        smart_str(u"Certification required"),
        smart_str(u"Year of last graduation"),
        smart_str(u"Marks PG"),
        smart_str(u"Marks UG"),
        smart_str(u"Marks XII"),
        smart_str(u"Marks X"),
        smart_str(u"Number of positions"),
        smart_str(u"Bond details"),
        smart_str(u"Bond duration"),
        smart_str(u"Compensation"),
        smart_str(u"Work location"),
        smart_str(u"Constraint location"),
	])
    requirements = Requirements.objects.raw(
            'SELECT d.id, created, p.name, jobTitle, skills, gender, certification, lastGradYear, '
            'marksPG, marksUG, marks10, marks12, numberOfPositions, bondDetails, bondDuration, '
            'compensation, d.location, constraintLocation from pma_demand as d '
            'INNER JOIN pma_partner as p on partner_fk = p.id INNER JOIN pma_demand_skills on demand_id = d.id '
            'WHERE created BETWEEN \'' + startdate + ' \' AND \'' + enddate + '\';'
    )
    for req in requirements:
        writer.writerow([
		    smart_str(req.id),
		    smart_str(req.created),
            smart_str(req.name),
		    smart_str(req.jobTitle),
            smart_str(req.skills),
            smart_str(req.gender),
            smart_str(req.certification),
            smart_str(req.lastGradYear),
            smart_str(req.marksPG),
            smart_str(req.marksUG),
            smart_str(req.marks12),
            smart_str(req.marks10),
            smart_str(req.numberOfPositions),
            smart_str(req.bondDetails),
            smart_str(req.bondDuration),
            smart_str(req.compensation),
            smart_str(req.location),
            smart_str(req.constraintLocation),
	    ])
    return response

@login_required
def special(request):
    return HttpResponse('You are logged in.')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponseRedirect("Your account was inactive")
        else:
            print("Someone tried to login and failed.")
            print("They used username : {} and password : {}".format(username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dashboard/login.html', {})

placementdashboard/templates/dashboard/activeDrives.html
{% extends 'dashboard/base.html' %}
{% block body_block %}
{% if user.is_authenticated %}
<div class="jumbotron jumbotron-fluid">
        <h1 align = "center" style = "font-size : 25pt"> ACTIVE DRIVES REPORT </h1>
</div>
<div class="jumbotron jumbotron-fluid">
     <table class="table">
                <tr>
                    <th>Sl No</th>
                    <th>Partner Name</th>
                    <th>Drive Start Date</th>
                </tr>
                {% for drive in activeDrives %}
                <tr>
                    <td>{{drive.slno | floatformat}}</td>
                    <td>{{drive.name}}</td>
                    <td>{{drive.date}}</td>
                </tr>
                {% endfor %}
            </table>
            </div>
{% else %}
    <meta http-equiv="Refresh" content="0; url= login">
{% endif %}
{% endblock %} 

placementdashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity = "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel = "stylesheet" type = "text/css" href = " {% static 'css/style.css' %}">
  </head>
</head>
<body>

  <nav style = "height : 100px" class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div>
        <ul class="nav navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}
          <li>
            <div>
                {% if user.is_authenticated %}
              <a class="navbar-brand" href="{% url 'index' %}">
                {% else %}
                <a class="navbar-brand" href="{% url 'user_login' %}">
                  {% endif %}
                <img src="https://www.talentsprint.com/misc/TS-Website/images/logo.png" id="nav-icon" alt="Icon" height="70vh"/>
              </a>
          </li>
          {% if user.is_authenticated %}
          <li id = "home-nav-item"> <a style = "font-size : 15pt; margin : 25px 10px 25px 30px" href = "{% url 'index' %}"> Home </a> </li>
          
          <li><a style = "font-size : 15pt; margin : 25px 0px" href="{% url 'logout' %}">Logout</a></li>

          {% endif %}
          </ul>

          {% if user.is_authenticated %}
          <ul  class = "nav navbar-nav navbar-right">
          <li style = "float : right; margin: 17px 0 0 0; font-size : 15pt" id="welcome">{{ user.username }}</li>
          {% endif %}

          </ul>
      <div>
    </div>
  </nav>

  <div class = "container">
    {% block body_block %}
    {% endblock %}

  </div>
</body>
</html>

placementdashboard/templates/dashboard/drivesReport.html
{% extends 'dashboard/base.html' %}
{% block body_block %}
{% if user.is_authenticated %}

<div class="jumbotron jumbotron-fluid">
        <h1 align = "center" style = "font-size : 25pt"> DRIVES REPORT </h1>
</div>

<div class="wrapper">
<form method="post" action="{% url 'dashboard:getDrivesReport' %}" download>
  {% csrf_token %}
      <p>Enter start date: </p> <input class = "date" type="date" id="startDate" class="fadeIn second" name="startDate" placeholder="Enter start date" required>
      <br>
      <p>Enter end date: </p>
      <input class="date" type="date" id="endDate" class="fadeIn third" name="endDate" placeholder="Enter end date" required>
      <br>
      <div class="wrapper">
      <input type="submit" class="fadeIn fourth" value="Show table">
      </div>
  </form>
  </div>
    {% if drives is not None %}
<div class="jumbotron jumbotron-fluid">
     <table class="table">
                <tr>
                    <th>Date</th>
                    <th>Drive Name</th>
                    <th>Round Number</th>
                    <th>Skills</th>
                    <th>No. of Positions</th>
                    <th>Compensation</th>
                    <th>Round Name</th>
                </tr>
                {% for drive in drives %}
                <tr>
                    <td>{{drive.date}}</td>
                    <td>{{drive.name}}</td>
                    <td>{{drive.roundNumber}}
                    <td>{{drive.skills}}</td>
                    <td>{{drive.numberOfPositions}}</td>
                    <td>{{drive.compensation}}</td>
                    <td>{{drive.rounds}}</td>
                </tr>
                {% endfor %}
            </table>
            </div>
            {% endif %}


    {% else %}
      <meta http-equiv="Refresh" content="0; url = ">
    {% endif %}

{% endblock %} 

placementdashboard/templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block headcontent %}
    <style>
    #home-nav-item {
        display : none;
    }
    </style>
{% endblock %}
{% block body_block %}
{% if user.is_authenticated %}

<div class="container">

    <div class="jumbotron jumbotron-fluid">
        <h1 align = "center" style = "font-size : 30pt"> PLACEMENT DASHBOARD </h1>
    </div>


    <div align = "center">
    <p style = "display : inline">
    <a class = "button" href="{% url 'requirements' %}" requirements><b> Job Offers </b> </a>
    </p>
    <p style = "display : inline">
    <a class = "button" href="{% url 'selfPlaced' %}" requirements> <b> Self - placed Trainees </b> </a>
    </p>
    <p style = "display : inline"> 
    <a class = "button" href="{% url 'activeDrives' %}" requirements> <b> Active Drives </b> </a>
    </p>
    <p style = "display : inline">
    <a class = "button" href="{% url 'drivesReport' %}" requirements> <b> Drives Report </b> </a>
    </p>
    </div>
    
    {% else %}
    <meta http-equiv="Refresh" content="0; url= login">
    {% endif %}

    {% endblock %}

placementdashboard/templates/dashboard/login.html
{% extends 'dashboard/base.html' %}
{% block body_block %}
<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="https://www.talentsprint.com/misc/TS-Website/images/logo.png" id="icon" alt="Icon" />
    </div>

    <!-- Login Form -->
    <form method="post" action="{% url 'dashboard:user_login' %}">
                {% csrf_token %}
      <input type="text" id="login" class="fadeIn second" name="username" placeholder="Username">
      <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password">

      <input style = "font-weight : bold" type="submit" class="fadeIn fourth" value="LogIn">
    </form>

    <!-- Remind Password -->
    <!-- <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div> -->

  </div>
</div>

{% endblock %} 

placementdashboard/templates/dashboard/requirements.html
{% extends 'dashboard/base.html' %}
{% block body_block %}
{% if user.is_authenticated %}

<div class="jumbotron jumbotron-fluid">
        <h1 align = "center" style = "font-size : 25pt"> JOB OFFERS </h1>
</div>

<div class="wrapper">
<form method="post" action="{% url 'dashboard:download_csv' %}" download>
  {% csrf_token %}
      <p>Enter start date: </p> <input class = "date" type="date" id="startDate" class="fadeIn second" name="startDate" placeholder="Enter start date" required>
      <br>
      <p>Enter end date: </p>
      <input class="date" type="date" id="endDate" class="fadeIn third" name="endDate" placeholder="Enter end date" required>
      <br>
      <div class="wrapper">
      <input type="submit" class="fadeIn fourth" value="Generate report">
      </div>
    <!-- <a class = "button" href="{% url 'dashboard:download_csv' %}" download> Generate CSV </a> -->
  </form>
  </div>  


    {% else %}
      <meta http-equiv="Refresh" content="0; url = ">
    {% endif %}

{% endblock %} 

placementdashboard/templates/dashboard/selfPlaced.html
{% extends 'dashboard/base.html' %}
{% block body_block %}
{% if user.is_authenticated %}
<div class="jumbotron jumbotron-fluid">
        <h1 align = "center" style = "font-size : 25pt"> SELF - PLACED TRAINEES </h1>
</div>

<form method="post" action="{% url 'dashboard:getSelfPlaced' %}">
  {% csrf_token %}

      <p align = center>Enter Batch ID: </p>
      <div class="wrapper">
        <input style = "width : 30vw" type="text" id="batchID" class="batch second"
        name="batch ID" placeholder="Batch ID" required>
      </div>
      <div class="wrapper">
        <input type="submit" class="fadeIn fourth" value="Show Table">
      </div>

    <!-- <a class = "button" href="{% url 'dashboard:download_csv' %}" download> Generate CSV </a> -->
  </form>
{% if selfPlacedStudents is not None %}
<div class="jumbotron jumbotron-fluid">
     <table class="table">
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Batch ID</th>
                    <th>Trainee ID</th>
                    <th>Skills</th>
                    <th>Company Name</th>
                    <th>Email ID</th>
                    <th>Mobile No</th>
                    <th>Year of Graduation</th>
                    <th>College Name</th>
                </tr>
                {% for student in selfPlacedStudents %}
                <tr>
                    <td>{{student.firstName}}</td>
                    <td>{{student.lastName}}</td>
                    <td>{{student.batch}}
                    <td>{{student.id}}</td>
                    <td>{{student.skill}}</td>
                    <td>{{student.selfPlacedWith}}</td>
                    <td>{{student.email}}</td>
                    <td>{{student.mobile}}</td>
                    <td>{{student.lastGradYear}}</td>
                    <td>{{student.collegeName}}</td>
                </tr>
                {% endfor %}
            </table>
            </div>
            {% endif %}
{% else %}
    <meta http-equiv="Refresh" content="0; url= login">
{% endif %}
{% endblock %}